---
- name: localhost playbook
  hosts: localhost
  gather_facts: false
  tasks:

  - name: deactivate PermitRootLogin
    ansible.builtin.lineinfile:
      path: "/etc/ssh/sshd_config"
      line: "PermitRootLogin prohibit-password"
      state: present
      #notify:
      #  - restart sshd

  - name: ensure PermitRootLogin is not activated
    ansible.builtin.lineinfile:
      path: "/etc/ssh/sshd_config"
      line: "PermitRootLogin yes"
      state: absent
      #notify:
      #  - restart sshd
