---
- name: localhost playbook
  hosts: localhost
  gather_facts: false
  tasks:

  - name: deactivate PermitRootLogin
    ansible.builtin.lineinfile:
      path: "/etc/ssh/sshd_config"
      line: "PermitRootLogin prohibit-password"
      state: present
    register: enable_sshd

  - name: ensure PermitRootLogin is not activated
    ansible.builtin.lineinfile:
      path: "/etc/ssh/sshd_config"
      line: "PermitRootLogin yes"
      state: absent
    register: disable_root

  - name: restart sshd
    service:
      name: sshd
      state: restarted
    when: enable_sshd.changed or disable_root.changed

